-   id: black
    name: check black
    description: Check python files formatting with black
    entry: black --skip-string-normalization --check
    language: python
    types: [python]
    stages: [commit, manual]
-   id: isort
    name: check isort
    description: Check imports order with isort
    entry: isort --check-only
    language: python
    types: [python]
    stages: [commit, manual]
-   id: flake8
    name: check flake8
    description: Check files syntax with flake8
    entry: flake8 --inline-quotes "'" --docstring-quotes '"' --multiline-quotes '"'
    language: python
    types: [python]
    stages: [commit, manual]
-   id: tests
    name: run tests
    description: Run unit tests
    entry: pytest --cov-report=term-missing --cov-fail-under=80 tests
    language: python
    pass_filenames: false
    always_run: true
    stages: [commit, manual]
